# Generated by Django 3.0.3 on 2020-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('zone', models.CharField(choices=[('RED', 'Red'), ('Orange', 'Orange'), ('Green', 'Green')], max_length=10)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
