# Generated by Django 3.0.3 on 2020-05-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='population',
        ),
    ]
