# Generated by Django 3.0.3 on 2020-05-19 06:59

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar', models.IntegerField(validators=[tickets.models.twelvedigit])),
                ('zone', models.CharField(choices=[('RED', 'Red'), ('Orange', 'Orange'), ('Green', 'Green')], max_length=10)),
                ('passengers', models.IntegerField(validators=[tickets.models.crowd])),
            ],
        ),
    ]
